### ISSUE TITLE
Doesnt turn off maintenance - escaping backslash remains in config.php

### ISSUE THREAD

**Issue by mjschrod** [julianpoemp/oc-backup#2]
Hello Julian and thx for you work.

I had a problem with the script. It didnt turn off the maintenance mode.
Is there really the need for escaping?

`enable_maintenance_mode() {
  log "-> Enable maintenance mode..."
  configFile="${configFile//\\'maintenance\\' => false/\\'maintenance\\' => true}"
  echo "${configFile}" > "${configPath}"
}

disable_maintenance_mode() {
  log "-> Disbale maintenance mode..."
  configFile="${configFile//\\'maintenance\\' => true/\\'maintenance\\' => false}"
  echo "${configFile}" > "${configPath}"
}`

My Installation (Debian on a Raspberry) only works without:

`enable_maintenance_mode() {
  log "-> Enable maintenance mode..."
  configFile="${configFile//'maintenance' => false/'maintenance' => true}"
  echo "${configFile}" > "${configPath}"
}

disable_maintenance_mode() {
  log "-> Disbale maintenance mode..."
  configFile="${configFile//'maintenance' => true/'maintenance' => false}"
  echo "${configFile}" > "${configPath}"
}`

**Comment by julianpoemp** [comment]
Hi @presskopf,

In my case escaping is needed. Without escaping enable_maintenance_mode() returns

````
...
maintenance => true
...
````

instead of

````
...
'maintenance' => true
...
````

and makes the configuration invalid.

What is the output of the following comannds if you paste them in your console?

````bash
test="'maintenance' => false"
echo "$test"  | sed "s/'maintenance' => false/'maintenance' => true/g"
````
